### ISSUE TITLE
Improving Front-End Code and Repository Structure

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#22]
**Problem:** The current front-end code and repository structure require fixes to enhance clarity and it is difficult of replication. For instance, the repository's organisation includes a mix of development and deployment files in the public folder. We also will use [LitElements](https://lit.dev/) library to improve the maintainability and scalability of the project components

**ToDo**
- [x]  **Redesign of Repository Structure:** We will restructure the repository to improve its organization and make it more intuitive to navigate. This will facilitate better understanding of the codebase and streamline replication processes.
- [x] **Transition to [LitElements](https://lit.dev/):** We have made the decision to adopt LitElements for creating front-end templates. This transition involves converting existing vanilla JavaScript components to LitElements, without utilizing the shadow DOM.

**Comment by JJ** [comment]
In general, issues should describe a problem. They should serve as a reminder, but in order to be correct, they should state what problem you're trying to solve, because when you create code issues are the yardstone you are going to measure it against. If you just describe a task it's impossible to measure anything: done the task, you're good. OTOH, if you say "Use best practices for repository layout", that's something the resulting measures can be judged against

**Comment by sergiomrebelo** [comment]
@JJ, I initially opened this issue as a reminder to organise the repository structure. However, during the process, I made the decision to parse the front-end components for LitElements. Sorry, by the confusion.  I have updated the issue description and name to reflect this change.

**Comment by sergiomrebelo** [comment]
The parsing of the front-end components has been completed successfully. I conducted tests using the same Cypress test that was used before the parsing, and I can confirm that the form now runs as expected.
